baseurl = "https://heehoposting.xyz/"
title = "Heehoposting"
theme = "whiteplain"
languageCode = "en"
# Disqus shortname
disqusShortname = "Heehoposting"
# google analytics tracking id
googleAnalytics = "Toracking ID"

[caches]
  [caches.images]
    dir = ':cacheDir/images"

[params]
  # whether to use CDN or local file for fontawesome
  #useCDN = false
  # whether to include external sharing scripts and icons for twitter, facebook and co.
  #showShareIcons = false
  # Date format
  #dateFormat = "January 2, 2006"

# This is displayer in About page.
[params.author]
  name = "Jackson Darman"
  # Gravatar or Abatar image
  #gravatar = "Gravatar email or MD5 Hash"
  avatar = "/avatar.jpg"

  github = "hackisonjd"
  linkedin = "jacksondarman"
  email = "jackson@darman.dev"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# Header Menu
[[menu.main]]
  name = "Categories"
  identifier = "categories"
  url = "/categories/"
  weight = 1
[[menu.main]]
  name = "Tags"
  identifier = "tags"
  url = "/tags/"
  weight = 2
[[menu.main]]
  name = "Archives"
  identifier = "archives"
  url = "/archives/"
  weight = 3
[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"
  weight = 4

# Footer Menu
[[menu.footer]]
  name = "About"
  weight = 1
  identifier = "about"
  url = "/about/"